### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ponduzn** [esx-community/esx_outlawalert#5]
Error resuming coroutine: citizen:/scripting/lua/Messagepack.lua:830: missing bytes
stack traceback:
[C]: in function 'error'
citizen:/scripting/lua/Messagepack.lua:830: in method 'underflow'
citizen:/scripting/lua/Messagepack.lua:465: in field 'any'
citizen:/scripting/lua/Messagepack.lua:860: in field 'unpack'
citizen:/scripting/lua/Messagepack.lua:628: in field 'Trim'
@esx_outlawalert/client/main.lua:186: in function <@esx_outlawalert/client/main.lua:172>

which refers to this line:
"local plate = ESX.Math.Trim(GetVehicleNumberPlateText(vehicle))"

Not sure how to fix this myself

**Comment by HawaiiBeach** [comment]
Update esx
